language: python

python:
    - "3.8"

cache: pip

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make build

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: r/tcCNIBOKqst794MWOlfGFBVJ847eAT58Dhp0c6DQFx8PuRT5JPYrtX2GqIYd6HBGUwif1hEo8OtGVebpigJvAa0pIgPQKEVQrHkZue/4vop2NDPL5QqKhzgW6B5XeWqt/ohIo1kEiec+qGOJtdKmQusUE/cL/t9QrVbFvP4gNwcU/8BbmnUx6tLLCyvVNdpdEASOQGjRp/h5JSA9s5d3L1CoD76wU6isnHZbty2PqmcayOe1F+VVom6Bk2eJowPULixww6gRfjhzNrV7t1VIo4Qe2GqjFTRTNc2lfxbfbQeGIFn76pOWZJpqxcIruF7ycBrYfYYlXB+/Az4qEoyr7BpgIefFLXX8eybZ5PVocglTkeDyVgMLE/YUp5vP6DZw5eJTvcdNPRi8ycZPRV5F/zFAoiEcXXxmP97I6fZifuTy7jFkO9s0F836joH2n5kxEY5O+8JronkUbksXV7fbonQF6mZPj1MGZwFZwi8dnwU9OfCxhF/dclwpE7BFh1VMM+6//2jh85FNJUCW5z6VqubRC4KS4elY78uKAOS0SYliawpMj2EYx4IFGrMYVCtSlxYV2J0A0XtQgOC+wwLaD3/iNtNxVJLkhufcN2op6EXN4lHW9EBywF50LP7BPjp8WOirbtT4QDI8esLTcL3M0WX97mNHdmvQhZOgVBLgY=
  skip_cleanup: true
  skip_existing: true
  on:
    branch: main

